// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/location-widget/Card.tsx": () => import("../components/mockups/location-widget/Card.tsx"),
  "./components/mockups/location-widget/Minimal.tsx": () => import("../components/mockups/location-widget/Minimal.tsx"),
  "./components/mockups/location-widget/Pill.tsx": () => import("../components/mockups/location-widget/Pill.tsx")
};
